### ISSUE TITLE
Available for classic?

### ISSUE THREAD

**Issue by Rudikuul** [muellerj/Prot#1]
Hi there,

Just a quick question.
Will this be available for classic?
(And by available i mean reworked so that it works with the new API)

This would make rolling a warrior and tanking dungeons with it a lot more appealing!

Thanks in advance

**Comment by muellerj** [comment]
Hi,

I'm afraid I am not planning on playing the reworked Classic and hence have no idea what the API looks like.

Please feel free to fork the project if you fancy. If Blizzard documents the APIs it’s willing to expose, translating the plugin should not be too hard. It could however be the case, that they are a lot more restrictive and this will not work at all.

Hope this helps!

**Comment by Rudikuul** [comment]
I'm afraid I'm not very knowledgeable when it comes to this stuff.
I heard the API is a lot more restrictive, especially the CallSpellByName function, or something like that anyways.

To counter automation.

So I dont know what the possibilities are and all.

Thanks anyways for the reply!
